# Generated by Django 4.2.24 on 2025-09-14 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['year', 'name']},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['course__year', 'name']},
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='capacity',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='schedule',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='degree',
            field=models.CharField(choices=[('PROFESSOR', 'Профессор'), ('DOCENT', 'Доцент'), ('LECTURER', 'Лектор'), ('ASSISTANT', 'Ассистент'), ('TEACHER', 'Мугалим')], default='TEACHER', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('group', 'day', 'start_time'), ('teacher', 'day', 'start_time')},
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.timeslot'),
        ),
    ]
