# Generated by Django 4.2.23 on 2025-09-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default='...', max_length=50),
        ),
    ]
