# Generated by Django 4.2.23 on 2025-09-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userprofile_options_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='marked_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Белгиленген убакыт'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by_student',
            field=models.BooleanField(default=False, verbose_name='Студент тарабынан белгиленди'),
        ),
    ]
