# Generated by Django 4.2.24 on 2025-09-09 14:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attendance_created_at_student_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='student',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='parents', to='core.student'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
        ),
    ]
