# Generated by Django 5.2.6 on 2025-10-01 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_attendance_marked_at_attendance_marked_by_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['day', 'time_slot__order'], 'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписаниелер'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['order'], 'verbose_name': 'Убакыт периоду', 'verbose_name_plural': 'Убакыт периоддору'},
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('group', 'day', 'time_slot'), ('teacher', 'day', 'time_slot')},
        ),
        migrations.AddField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активдүү'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активдүү'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Дүйшөмбү'), ('Tuesday', 'Шейшемби'), ('Wednesday', 'Шаршемби'), ('Thursday', 'Бейшемби'), ('Friday', 'Жума'), ('Saturday', 'Ишемби'), ('Sunday', 'Жекшемби')], max_length=10, verbose_name='Күн'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject', verbose_name='Сабак'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.teacher', verbose_name='Мугалим'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.timeslot', verbose_name='Убакыт периоду'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(verbose_name='Аяктоо убакыты'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Период аты'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Тартиби'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(verbose_name='Башталуу убакыты'),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
    ]
